!if %not(%variable_exists("$BGCOLOR"))
!$BGCOLOR = "#FFFFFE"
!endif

skinparam backgroundColor $BGCOLOR
skinparam useBetaStyle false

' skinparam roundcorner 20

skinparam title {
	FontColor	                 #000
	BorderColor	                 #c2c2c2
	' FontSize	    	         16
	BorderRoundCorner            8
	BorderThickness 	         1
	BackgroundColor              #f5f5f5-#f2f2f2
}

skinparam rectangle {
	BorderThickness 2
	BorderColor #gray
}

!definelong MethodClient(e_alias, e_label)
rectangle "e_label" as e_alias #lawngreen
!enddefinelong

!definelong MethodManager(e_alias, e_label)
rectangle "e_label" as e_alias #yellow
!enddefinelong

!definelong MethodEngine(e_alias, e_label)
rectangle "e_label" as e_alias #orange
!enddefinelong

!definelong MethodAccessor(e_alias, e_label)
rectangle "e_label" as e_alias #lightgray
!enddefinelong

!definelong MethodUtil(e_alias, e_label)
rectangle "e_label" as e_alias #violet
!enddefinelong

!definelong MethodResource(e_alias, e_label)
rectangle "e_label" as e_alias #aqua
!enddefinelong

!definelong MethodDb(e_alias, e_label)
database "e_label" as e_alias #aqua
!enddefinelong
